apiVersion: batch/v1
kind: Job
metadata:
  name: tcp-node-1
  labels:
  parallelism: 1
  namespace: crail
spec:
  parallelism: 1
  template:
    metadata:
      labels:
        name: datanode-tcp
        app: datanode-tcp
    spec:
      restartPolicy: OnFailure
      containers:
      - name: datanode-tcp
        image: crail-elastic
        #image: asqasq/crailk8selastic
        imagePullPolicy: Never
        env:
        - name: NAMENODE_HOST
          value: crail-nameserver
        - name: INTERFACE
          value: eth0
        securityContext:
           readOnlyRootFilesystem: false
        command: ['/bin/bash']
        args: ["-c","start-stats.sh; start-crail-docker.sh datanode"]
        volumeMounts:
        - mountPath: /hugepages-2Mi
          name: hugepage-2mi
        resources:
          limits:
            hugepages-2Mi: 1024Mi
            memory: 100Mi
          requests:
            memory: 100Mi
      volumes:
      - name: hugepage-2mi
        emptyDir:
          medium: HugePages-2Mi
      nodeSelector:
        beta.kubernetes.io/os: linux
