apiVersion: batch/v1
kind: Job
metadata:
  name: tcp-node-1
  namespace: crail
spec:
  parallelism: 1
  template:
    metadata:
      labels:
        name: datanode-tcp
        app: datanode-tcp
    spec:
      restartPolicy: Never
      containers:
      - name: datanode-tcp
        image: gcr.io/spot-storage-elasticity/crail-elastic
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","python3 /crail/bin/stop-crail-docker.py; bash /crail/bin/stop-crail-java.sh"]
        env:
        - name: NAMENODE_HOST
          value: crail-nameserver
        - name: INTERFACE
          value: eth0
        - name: STORAGELIMIT
          value: "21474836480"
        - name: STORAGELIMIT_IN_G
          value: "20"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        securityContext:
           readOnlyRootFilesystem: false
           privileged: true
           allowPrivilegeEscalation: true
        volumeMounts:
        - mountPath: /dev
          name: dev
        command: ['/bin/bash']
        args: ["-c","collectl --export lexpr | tee collectl.txt & start-crail-docker.sh datanode; echo Done"]
        #args: ["-c","start-crail-docker.sh datanode &> out.log"]
        resources:
          limits:
          requests:
            memory: 2Gi
      volumes:
      - name: dev
        hostPath:
          path: /dev
      nodeSelector:
        #kubernetes.io/hostname: gke-cluster-1-datanode-2-af1fbb88-skmx
        beta.kubernetes.io/os: linux
